version: '3'

services:
  mqtt:
    image: eclipse-mosquitto:2.0.15
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - "./mosquitto/conf:/mosquitto/config:ro"
      - "./mosquitto/data:/mosquitto/data:rw"
      - "./mosquitto/log:/mosquitto/log:rw"
      

    